services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    ports:
      - 5050:80
    volumes:
      - ./build:/srv
    environment:
      - FB_USERNAME=admin
      - FB_PASSWORD=admin